name: dockerhub-ci-staging

on:
  push:
    branches:
      - 'staging'
    tags:
      - 'v*.*.*'

jobs:
  stagingToMain:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/checkout@v3
      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          commit-message: Auto Pull Request
          title: Automated PR branch staging to Prod
          body: After you valid the changes in staging environnement, just press the button, the production are to be released
          branch: ${{ github.ref }} # The branch where you commit
          base: main # Don't forget to specify the right base branch here
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        # with:
        #   images: getshitdonewild/getshitdone-front-staging
        with:
          # list of Docker images to use as base name for tags
          images: |
            name/app
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile-staging
          push: true
          # tags: getshitdonewild/getshitdone-front-staging:latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
